### PR TITLE
Add margin to the messages

### PR DESCRIPTION
**Pull request by sinmineryt**
Or else messages will display under the username field

### CODE REVIEW

**Comment by aquaticdosDev** [comment]
yes

**Comment by random-development-hub** [comment]
nice ok

**Comment by sinmineryt** [comment]
Why is everyone here now

**Review by random-development-hub — COMMENTED** [review]
yes ok cool

**Comment by cedkim** [comment]
ok it is pernes that is good

**Comment by sinmineryt** [comment]
please approove my changes

**Comment by HappyDarion** [comment]
hey guys
i madrion

**Comment by HappyDarion** [comment]
im darion

**Comment by sinmineryt** [comment]
OR ELSE I CAN'T MERGE IDIOTS

**Comment by random-development-hub** [comment]
I LITERALLY APPROVED

**Comment by random-development-hub** [comment]
I'M CLOSING THIS

**Comment by HappyDarion** [comment]
can i approve
how do i approve

**Review by cedkim — COMMENTED** [review]
yes good

**Comment by aquaticdosDev** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOoo

**Comment by random-development-hub** [comment]
cedric
fucking
approve

**Comment by sinmineryt** [comment]
i hate you alex

**Comment by sinmineryt** [comment]
grafik

**Comment by cedkim** [comment]
i did approve

**Comment by HappyDarion** [comment]
I WANNA APPROVE

**Comment by random-development-hub** [comment]
WAIT SHIT

**Comment by sinmineryt** [comment]
wtf
alex

**Comment by cedkim** [comment]
imma switch devices real quick

**Comment by sinmineryt** [comment]
jUST REVIEWW AAAAAAAAAAAAAAAAAAAAAAAa

**Review by random-development-hub — APPROVED** [review]

**Comment by sinmineryt** [comment]
YES FINAK;LY

**Comment by sinmineryt** [comment]
omg

**Comment by sinmineryt** [comment]
was it that hard

**Comment by HappyDarion** [comment]
THANK YOU

**Comment by sinmineryt** [comment]
this is chaos

**Comment by sinmineryt** [comment]
this literally has been merged why are we still atalking here

**Pull request merged**
